### ISSUE TITLE
Single txt file or one txt file per channel?

### ISSUE THREAD

**Issue by skjerns** [EEGManyPipelines/templates#1]
In the instructions it is stated

```raw
2. A text file (.txt or .csv) with the number/label of channels that you identified as “bad
channels” [...]
```

I would interpret this as a simple txt file `excluded_channels.txt` with the content

```raw
C4, P1, P5
```

However, in your example structure it is now there as a folder (?), and it is named `Excluded sensors (txt files)`, so 'files' -> plural. Does this mean I should create a folder and inside put one txt file for each channel I excluded

ie. 
```raw
Subj01-
        -Excluded sensors (txt files)
                -C4.txt
                -P1.txt
                -P5.txt
Subj02
     [...]
```

Maybe you can adapt the template in such a way that it actually corresponds to what a final result would look like? that means, instead of a template, give an example! Currently, it is rather confusing.

**Comment by mcvinding** [comment]
I see this can cause confusion. It is a single file with a list of excluded electrodes per subject as in your first example. However, if you did the last, we will still manage.
